"""
Concatenation is the process of combining the two strings...
"""

# Concatenation of strings...
print("Sabari" + " " + "Vivek")

# It works as an operator if its integer...
print(21 + 8)

# It gives error if you try to concatenate string with an integer...
# print("Sabari " + 28)

# Solution 1 for above issue...
print("Sabari " + str(28))

# Solution 2 for above issue...
print("Sabari", 28)
