"""
Static variables and methods are belongs to the class...
Whereas Instance variables and methods are belongs to the object of the class...

# Instance Methods :
    * Instance Methods and Instance Variables are belongs to Object Memory...
    * Needs to be accessed using the object...
    * Has self keyword specified inorder to use the class objects...

# Static Methods :
    * Static Methods and Static Variables are belongs to Class Memory...
    * Should have @staticmethod before the method...
    * Should not be specified with self keyword like a normal method...
    * If we give self, it will be treated as a parameter instead of self...
    * It can be accessed using the class name...
    * Static methods can be access static stuffs...
"""


class A:
    # Static Variable...
    employee_name = "Sabari"

    def __init__(self, role, experience):
        self.role = role
        self.experience = experience

    def func_1(self):
        print("Role :", self.role)
        print("Experience :", self.experience)

    # Static Method...
    @staticmethod
    def func_2():
        print("Name :", A.employee_name)


obj = A("Automation Testing", "2 Years")
A.func_2()
obj.func_1()
