# Declaring the variable...
value = 10

# Printing the variable...
print(value)

# Here we are deleting the created variable...
del value

# Value won't be here since we deleted the variable already...
print(value)
