# Max and Min functions are in built function in java to find the maximum and minimum...

# Maximum in given integers...
print(max(10, 39, 43.7, 54, 23, 223.5, 22.90))

# Minimum in given integers...
print(min(10, 39, 43.7, 54, 23, 223.5, 22.90))

# Maximum length in given string's (If the length is equal, it will go for ASCII comparison)...
print(max("Orange", "Blue", "Yellow", "Green", "Red"))

# Minimum length in given string's...
print(min("Orange", "Blue", "Yellow", "Green", "Red"))
